name: github_image

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/github_image.yml'
      - '.github/docker/dl-packs/*'
      - '.github/docker/firmware/*'
      - '.github/docker/generate/*'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/docker/dl-packs/*'
      - '.github/docker/firmware/*'
      - '.github/docker/generate/*'
      - '!.github/workflows/**'
  schedule:
    - cron: '45 18 28 * *'
  workflow_dispatch:

concurrency:
  group: ${{ (github.event_name == 'pull_request') && github.workflow && '-' && github.event.pull_request.number || github.workflow }}
  cancel-in-progress: ${{ (github.event_name == 'pull_request') && true || true }}

jobs:
  matrizifizieren:
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch'

    outputs:
      gitsha: ${{ steps.parse.outputs.gitsha }}
      images: ${{ steps.parse.outputs.img }}

    steps:

      - name: clone
        uses: actions/checkout@v6

      - name: parse
        id: parse
        run: |
          IMAGES="$(find .github/docker -mindepth 1 -maxdepth 1 -type d | sed 's|.github/docker/||')"
          IMAGES="$(echo "$IMAGES" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
          IMAGES_JSON=$(echo "$IMAGES" | awk 'NF {printf "\"%s\",", $0}' | sed 's/,$//')
          [ -n "$IMAGES_JSON" ] && echo "img=[$IMAGES_JSON]" >> $GITHUB_OUTPUT || exit 1
          echo "gitsha=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: vars
        id: vars
        run: |
          echo "################################################################"
          echo "IMAGES=[$IMAGES_JSON]"
          echo "################################################################"
          echo "GITSHA=${{ github.sha }}"

  build:
    permissions:
      contents: read
      packages: write
    needs: matrizifizieren
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.matrizifizieren.outputs.images) }}
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng' || github.event_name == 'workflow_dispatch'

    steps:

      - name: clone
        uses: actions/checkout@v6
        with:
          ref: ${{ fromJson(needs.matrizifizieren.outputs.gitsha) }}

      - name: prepare
        id: prepare
        run: |
          OWNER="$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"
          [ -z "$OWNER" ] && OWNER="$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')"
          [ -n "$OWNER" ] && echo "owner=$OWNER" >> $GITHUB_OUTPUT || exit 1
          IMAGE="$(echo "${{ matrix.image }}" | sed 's/.*_//')"
          [ -n "$IMAGE" ] && echo "image=$IMAGE" >> $GITHUB_OUTPUT || exit 1
          for x in Dockerfile entrypoint.sh; do ln -s .github/docker/$IMAGE/$x; done
          echo "################################################################" && echo "URI=$OWNER/$IMAGE"

      - name: login
        if: ${{ github.repository == 'freetz-ng/freetz-ng' || github.event_name != 'pull_request' }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.repository == 'freetz-ng/freetz-ng' || github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.prepare.outputs.owner }}/${{ steps.prepare.outputs.image }}:latest
